### ISSUE TITLE
Transparent setting for the panel under general tab doesn't do anything

### ISSUE THREAD

**Issue by zamolxe** [yesoreyeram/yesoreyeram-boomtable-panel#42] opened 2018-11-17 10:13 UTC
Setting the panel as transparent under the general tab, doesn't apply the setting.

<img width="1362" alt="screen shot 2018-11-17 at 11 09 31" src="https://user-images.githubusercontent.com/1435948/48659950-a66dc200-ea59-11e8-861c-bcccbe443aa2.png">

**Comment by yesoreyeram** [comment] 2018-11-18 18:48
HI @zamolxe - Thanks for notifying this issue. I had a quick look and I couldn't find the root cause.  If you know the root cause, please send a PR.  I will debug later.

**Comment by zamolxe** [comment] 2018-11-18 19:12
I investigated a bit more the behaviour, and it turned out that reloading the dashboard fixes the issue. I suppose you can close this one as it looks like not related to the plugin itself.

**Comment by yesoreyeram** [comment] 2018-11-18 21:35
It is strange. As you mentioned this setting is not handled by panel but grafana itself.  **Reloading the dashboard helps.**

I am closing this comment and reopen later if required. BTW, if you notice any other bugs please report. As well as feature requests are welcome.

**Closed by yesoreyeram** 2018-11-18 21:35 UTC
