### ISSUE TITLE
[Bug] Image rendering via grafana API doesn't work

### ISSUE THREAD

**Issue by sriverg2** [yesoreyeram/yesoreyeram-boomtable-panel#143] opened 2020-08-06 19:37 UTC
**Describe the bug**
Grafana has an API and there is a method to get rendered picture with request like:
 https://my.grafana.address.com/render/d-solo/board_id/_?from=1596585600000&height=500&panelId=26&theme=light&to=1596671999000&width=1000
It works well with any panel type, except boom table panel. With Boom table panel we are getting 504 Gateway Time-out instead of picture.  Checked several times changing panel type

**Version Details:**
 - Grafana version : 6.6.0
 - Plugin version : 1.3.0

**Comment by yesoreyeram** [comment] 2020-08-12 13:02
Duplicate of #18 . 

If you still get the error with latest version, share more details about the error.

**Closed by yesoreyeram** 2020-08-12 13:02 UTC
Labels: bug
