### ISSUE TITLE
support sort in table header

### ISSUE THREAD

**Issue by zsq1314** [yesoreyeram/yesoreyeram-boomtable-panel#39] opened 2018-10-19 08:03 UTC
First thank you for the great plugin. it would be great to support sort in column headers. What is the plan of the feature?

**Comment by yesoreyeram** [comment] 2018-10-19 09:19
Yes. That is in pipeline. But not sure I will push in next 2 to 3 months. Sorry for that.

Duplicate of #33 . Hence closing.

**Closed by yesoreyeram** 2018-10-19 09:19 UTC
